### PR TITLE
New test cases

### PR DESCRIPTION
**Pull request by natlibesa**
Added two new test-fixtures, 16 & 17.

### CODE REVIEW

**Review by natlibfi-arlehiko — CHANGES_REQUESTED** [review]
Last commit is not signed.

**Review by natlibfi-arlehiko — CHANGES_REQUESTED** [review]
See comments in Slack.

**Comment by natlibesa** [comment]
Added test-fixtures for ProductFormat = AN; 22 & 23

**Review by natlibfi-arlehiko — CHANGES_REQUESTED** [review]
See comments in Slack.

**Review by natlibfi-arlehiko — CHANGES_REQUESTED** [review]
Still 59 changed files. Do this:

1. Checkout `next` and pull
2. Create a new branch
3. Add only the 6 new directories
4. Add only those directories and their contents with `git add`
5. Commit and push

**Pull request closed without merging**
